name-template: 'Release v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # Changes
  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
    collapse-after: 3
  - title: 'Improvements'
    labels:
      - 'enhancement'
    collapse-after: 3
  - title: 'Tests'
    labels:
      - 'test'
    collapse-after: 3
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'hotfix'
      - 'revert'
    collapse-after: 3
  - title: '🧰 Maintenance'
    labels:
      - 'docs'
      - 'chore'
      - 'build'
      - 'ci'
    collapse-after: 3

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'enhancement'
    branch:
      - '/refactor\/.+/'
      - '/perf\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'maintenance'
    files:
      - '*.md'
      - '*.txt'
      - '*.png'
      - '*.yml'
      - '*.xml'
    title:
      - '/chore/i'
      - '/docs/i'
    branch:
      - '/chore\/.+/'
      - '/docs\/.+/'
  - label: 'ci'
    files:
      - '.github/*'
      - '.ci/*'
  - label: 'test'
    branch:
      - '/test\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'code-changed'
    files:
      - '*.java'

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  patch:
    labels:
      - 'ci'
      - 'fix'
      - 'test'
      - 'hotfix'
      - 'maintenance'
  default: patch
