readerConfig.connectOptions.host = "localhost"
readerConfig.connectOptions.host = ${?PG_READER_HOST}
readerConfig.connectOptions.port = 5432
readerConfig.connectOptions.database = "experiment"
readerConfig.connectOptions.database = ${?POSTGRES_DATABASE}
readerConfig.connectOptions.user = ${POSTGRES_USER}
readerConfig.connectOptions.password = ${POSTGRES_PASSWORD}
readerConfig.connectOptions.connectTimeout = 2000
readerConfig.connectOptions.cachePreparedStatements = true
readerConfig.poolOptions.maxSize = 5
readerConfig.poolOptions.maxWaitQueueSize = 2000
readerConfig.retryCount = 3

writerConfig.connectOptions.host = "localhost"
writerConfig.connectOptions.host = ${?PG_WRITER_HOST}
writerConfig.connectOptions.port = 5432
writerConfig.connectOptions.database = "experiment"
writerConfig.connectOptions.database = ${?POSTGRES_DATABASE}
writerConfig.connectOptions.user = ${POSTGRES_USER}
writerConfig.connectOptions.password = ${POSTGRES_PASSWORD}
writerConfig.connectOptions.connectTimeout = 2000
writerConfig.connectOptions.cachePreparedStatements = true
writerConfig.poolOptions.maxSize = 3
writerConfig.poolOptions.maxWaitQueueSize = 2000
writerConfig.retryCount = 3
