readerConfig.connectOptions.host = "localhost"
readerConfig.connectOptions.port = 5432
readerConfig.connectOptions.database = "experiment"
readerConfig.connectOptions.user = "admin"
readerConfig.connectOptions.password = "admin123"
readerConfig.connectOptions.connectTimeout = 2000
readerConfig.connectOptions.cachePreparedStatements = true
readerConfig.poolOptions.maxSize = 5
readerConfig.poolOptions.maxWaitQueueSize = 2000
readerConfig.retryCount = 3

writerConfig.connectOptions.host = "localhost"
writerConfig.connectOptions.port = 5432
writerConfig.connectOptions.database = "experiment"
writerConfig.connectOptions.user = "admin"
writerConfig.connectOptions.password = "admin123"
writerConfig.connectOptions.connectTimeout = 2000
writerConfig.connectOptions.cachePreparedStatements = true
writerConfig.poolOptions.maxSize = 3
writerConfig.poolOptions.maxWaitQueueSize = 2000
writerConfig.retryCount = 3
