readerConfig.connectOptions.host = ${postgres.host}
readerConfig.connectOptions.port = ${postgres.port}
readerConfig.connectOptions.database = ${postgres.database}
readerConfig.connectOptions.user = ${postgres.user}
readerConfig.connectOptions.password = ${postgres.password}

writerConfig.connectOptions.host = ${postgres.host}
writerConfig.connectOptions.port = ${postgres.port}
writerConfig.connectOptions.database = ${postgres.database}
writerConfig.connectOptions.user = ${postgres.user}
writerConfig.connectOptions.password = ${postgres.password}
