openapi: 3.0.1
info:
  title: testlab
  description: testlab Service
  version: "1.0"
paths:
  /v1/experiments/name-availability:
    get:
      operationId: handle
      parameters:
      - name: x-project-key
        in: header
        required: true
        schema:
          type: string
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully validated experiment name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessNameAvailabilityResponse'
        "400":
          description: Invalid project key or experiment name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
  /v1/experiments/tags:
    get:
      operationId: getTagsHandle
      parameters:
      - name: x-project-key
        in: header
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved tags
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessTagsResponse'
        "400":
          description: Invalid project Key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
components:
  schemas:
    ErrorEntity:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        cause:
          type: string
    Failure:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ErrorEntity'
    NameAvailabilityResponse:
      type: object
      properties:
        isAvailable:
          type: boolean
        message:
          type: string
    SuccessNameAvailabilityResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/NameAvailabilityResponse'
    SuccessTagsResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TagsResponse'
    TagsResponse:
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
