openapi: 3.0.1
info:
  title: testlab
  description: testlab Service
  version: "1.0"
paths:
  /v1/allocation:
    get:
      operationId: getAllocationHandle
      parameters:
      - name: x-project-key
        in: header
        schema:
          type: string
      - name: x-user-Id
        in: header
        schema:
          type: string
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        "304":
          description: Successful Not Modified Response
        "400":
          description: Bad Request due to invalid/missing body params / header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "401":
          description: Bad Request due to invalid api-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
    post:
      operationId: allocationHandle
      parameters:
      - name: x-project-key
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AllocationRequest'
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        "304":
          description: Successful Not Modified Response
        "400":
          description: Bad Request due to invalid/missing body params / header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "401":
          description: Bad Request due to invalid api-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
  /v1/experiments:
    get:
      operationId: filterExperimentsHandle
      parameters:
      - name: x-project-key
        in: header
        required: true
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      - name: owner
        in: query
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
      - name: tag
        in: query
        schema:
          type: string
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
          default: 20
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        "400":
          description: Project Key is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
  /v1/experiments/{experimentId}:
    get:
      operationId: getExperimentHandle
      parameters:
      - name: x-project-key
        in: header
        required: true
        schema:
          type: string
      - name: experimentId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        "400":
          description: Experiment Id is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "404":
          description: Experiment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
  /v1/experiments/tags:
    get:
      operationId: getTagsHandle
      parameters:
      - name: x-project-key
        in: header
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved tags
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessTagsResponse'
        "400":
          description: Invalid project Key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
components:
  schemas:
    Success:
      type: object
      properties:
        data:
          type: object
    ErrorEntity:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        cause:
          type: string
    Failure:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ErrorEntity'
    AllocationRequest:
      type: object
      properties:
        experiments:
          type: array
          items:
            type: string
        attributes:
          $ref: '#/components/schemas/Attributes'
        guestId:
          type: string
        userId:
          type: string
    Attributes:
      type: object
      properties:
        model:
          type: string
        device:
          type: string
        platform:
          type: string
        build_version:
          type: string
        app_name:
          type: string
        os_version:
          type: string
        app_version:
          type: string
        build_number:
          type: string
    Experiment:
      type: object
      properties:
        experimentId:
          type: string
          format: uuid
        projectKey:
          type: string
        name:
          type: string
        description:
          type: string
        hypothesis:
          type: string
        status:
          type: string
          enum:
          - LIVE
          - PAUSED
          - DRAFT
          - CONCLUDED
          - TERMINATED
        type:
          type: string
          enum:
          - A/A
          - A/B
        guardrailHealthStatus:
          type: string
          enum:
          - WARNING
          - PASSED
          - NO_CHECKS_AVAILABLE
          - FAILED
        cohorts:
          type: array
          items:
            type: string
        variantWeights:
          $ref: '#/components/schemas/JsonObject'
        assignmentStrategy:
          type: string
          enum:
          - RANDOM
          - ROUND_ROBIN
        overrides:
          $ref: '#/components/schemas/JsonObject'
        ruleAttributes:
          $ref: '#/components/schemas/JsonObject'
        winningVariant:
          $ref: '#/components/schemas/JsonObject'
        exposure:
          type: integer
          format: int32
        threshold:
          type: integer
          format: int64
        startTime:
          type: integer
          format: int64
        endTime:
          type: integer
          format: int64
        createdBy:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        tags:
          type: string
        owner:
          type: string
    FilterExperimentsResponse:
      type: object
      properties:
        experiments:
          type: array
          items:
            $ref: '#/components/schemas/Experiment'
        pagination:
          $ref: '#/components/schemas/PaginationMeta'
    JsonObject:
      type: object
      properties:
        map:
          type: object
          additionalProperties:
            type: object
        empty:
          type: boolean
    PaginationMeta:
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int32
    SuccessFilterExperimentsResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/FilterExperimentsResponse'
    SuccessExperiment:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Experiment'
    SuccessTagsResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TagsResponse'
    TagsResponse:
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
