openapi: 3.0.1
info:
  title: testlab
  description: testlab Service
  version: "1.0"
paths:
  /v1/experiment:
    post:
      summary: Create a new experiment
      operationId: create
      parameters:
      - name: x-tenant-id
        in: header
        schema:
          type: string
          format: uuid
      - name: x-project-key
        in: header
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExperimentRequest'
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateExperimentResponse'
        "400":
          description: Invalid enum values for status or type
  /v1/experiment/{experiment_id}:
    patch:
      summary: Update experiment partially with optional tag replace
      operationId: update
      parameters:
      - name: x-tenant-id
        in: header
        schema:
          type: string
          format: uuid
      - name: x-project-key
        in: header
        schema:
          type: string
          format: uuid
      - name: experiment_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExperimentRequest'
      responses:
        "200":
          description: Updated successfully
          content:
            application/json:
              schema:
                type: boolean
        "400":
          description: Invalid enum values or validation constraints
  /v1/experiments/tags:
    get:
      operationId: getTagsHandle
      parameters:
      - name: x-project-key
        in: header
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved tags
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessTagsResponse'
        "400":
          description: Invalid project Key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failure'
components:
  schemas:
    CreateExperimentResponse:
      type: object
      properties:
        experimentId:
          type: string
          format: uuid
        status:
          type: boolean
        message:
          type: string
    CohortVariantWeights:
      required:
      - weights
      type: object
      allOf:
      - $ref: '#/components/schemas/VariantWeights'
      - type: object
        properties:
          weights:
            type: object
            additionalProperties:
              type: number
              format: double
    Condition:
      required:
      - operand
      - operandDataType
      - operator
      - value
      type: object
      properties:
        operand:
          type: string
        operandDataType:
          type: string
        operator:
          type: string
        value:
          type: string
    CreateExperimentRequest:
      required:
      - assignment_strategy
      - cohorts
      - created_by
      - description
      - hypothesis
      - name
      - owner
      - status
      - type
      - variant_weights
      type: object
      properties:
        project_key:
          type: string
          format: uuid
        tenant_id:
          type: string
          format: uuid
        experiment_id:
          type: string
          format: uuid
        name:
          maxLength: 64
          minLength: 1
          type: string
        description:
          maxLength: 255
          minLength: 0
          type: string
        hypothesis:
          maxLength: 1000
          minLength: 0
          type: string
        status:
          type: string
          enum:
          - LIVE
          - PAUSED
          - DRAFT
          - CONCLUDED
          - TERMINATED
        type:
          type: string
          enum:
          - A_B
        guardrail_health_status:
          type: string
          enum:
          - WARNING
          - PASSING
          - NO_CHECKS_AVAILABLE
          - FAILED
        metrics:
          maxItems: 10
          minItems: 0
          type: array
          items:
            maxLength: 10
            minLength: 0
            type: string
        cohorts:
          maxItems: 20
          minItems: 1
          type: array
          items:
            maxLength: 20
            minLength: 1
            type: string
        tags:
          maxItems: 20
          minItems: 0
          type: array
          items:
            maxLength: 20
            minLength: 0
            type: string
        owner:
          maxLength: 255
          minLength: 0
          type: string
        variant_weights:
          $ref: '#/components/schemas/VariantWeights'
        assignment_strategy:
          type: string
          enum:
          - RANDOM
          - ROUND_ROBIN
        rule_attributes:
          maxItems: 50
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/RuleAttributes'
        winning_variant:
          $ref: '#/components/schemas/VariantWeights'
        variants:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Variant'
        distribution_strategy:
          type: string
          enum:
          - RANDOM
          - ROUND_ROBIN
        assignment_domain:
          type: string
          enum:
          - MANUAL
          - COHORT
          - DEFAULT
        overrides:
          maxLength: 255
          minLength: 0
          type: string
        exposure:
          maximum: 100
          minimum: 0
          type: integer
          format: int32
        threshold:
          minimum: 0
          type: integer
          format: int64
        start_time:
          minimum: 0
          type: integer
          format: int64
        end_time:
          minimum: 0
          type: integer
          format: int64
        created_by:
          maxLength: 255
          minLength: 0
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ManualVariantWeights:
      required:
      - weights
      type: object
      allOf:
      - $ref: '#/components/schemas/VariantWeights'
      - type: object
        properties:
          weights:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
    RuleAttributes:
      required:
      - conditions
      - name
      type: object
      properties:
        name:
          type: string
        conditions:
          type: array
          items:
            $ref: '#/components/schemas/Condition'
    Variables:
      required:
      - dataType
      type: object
      properties:
        value:
          type: string
        key:
          type: string
        dataType:
          type: string
    Variant:
      required:
      - dataType
      type: object
      properties:
        displayName:
          type: string
        variables:
          type: array
          items:
            $ref: '#/components/schemas/Variables'
        dataType:
          type: string
    VariantWeights:
      type: object
      properties:
        type:
          type: string
          enum:
          - MANUAL
          - COHORT
          - DEFAULT
      discriminator:
        propertyName: type
    UpdateExperimentRequest:
      type: object
      properties:
        name:
          maxLength: 64
          minLength: 1
          type: string
        description:
          maxLength: 255
          minLength: 0
          type: string
        hypothesis:
          maxLength: 1000
          minLength: 0
          type: string
        status:
          type: string
          enum:
          - LIVE
          - PAUSED
          - DRAFT
          - CONCLUDED
          - TERMINATED
        type:
          type: string
          enum:
          - A_B
        guardrail_health_status:
          type: string
          enum:
          - WARNING
          - PASSING
          - NO_CHECKS_AVAILABLE
          - FAILED
        cohorts:
          maxItems: 20
          minItems: 1
          type: array
          items:
            maxLength: 20
            minLength: 1
            type: string
        variant_weights:
          $ref: '#/components/schemas/VariantWeights'
        assignment_strategy:
          type: string
          enum:
          - RANDOM
          - ROUND_ROBIN
        variants:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Variant'
        distribution_strategy:
          type: string
          enum:
          - RANDOM
          - ROUND_ROBIN
        assignment_domain:
          type: string
          enum:
          - MANUAL
          - COHORT
          - DEFAULT
        overrides:
          maxLength: 255
          minLength: 0
          type: string
        rule_attributes:
          maxItems: 50
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/RuleAttributes'
        winning_variant:
          $ref: '#/components/schemas/VariantWeights'
        exposure:
          maximum: 100
          minimum: 0
          type: integer
          format: int32
        threshold:
          minimum: 0
          type: integer
          format: int64
        start_time:
          minimum: 0
          type: integer
          format: int64
        end_time:
          minimum: 0
          type: integer
          format: int64
        tag:
          maxItems: 20
          minItems: 0
          type: array
          items:
            maxLength: 20
            minLength: 0
            type: string
        updated_by:
          maxLength: 255
          minLength: 0
          type: string
        end_date:
          type: string
    ErrorEntity:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        cause:
          type: string
    Failure:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ErrorEntity'
    SuccessTagsResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TagsResponse'
    TagsResponse:
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
