host="0.0.0.0"
port=8080
compressionLevel=1
compressionSupported=false
idleTimeout=8
logActivity=false
reusePort=true
reuseAddress=true
tcpFastOpen=true
tcpNoDelay=true
tcpQuickAck=true
tcpKeepAlive=true
useAlpn=false
