readerConfig.connectOptions.host = "localhost"
readerConfig.connectOptions.port = 3306
readerConfig.connectOptions.database = your_db
readerConfig.connectOptions.user = root
readerConfig.connectOptions.password = Ammupandu_57
readerConfig.connectOptions.connectTimeout = 2000
readerConfig.connectOptions.useAffectedRows = true
readerConfig.connectOptions.cachePreparedStatements = true
readerConfig.poolOptions.maxSize = 5
readerConfig.poolOptions.maxWaitQueueSize = 2000
readerConfig.retryCount = 3

writerConfig.connectOptions.host = "localhost"
writerConfig.connectOptions.port = 3306
writerConfig.connectOptions.database = your_db
writerConfig.connectOptions.user = root
writerConfig.connectOptions.password = Ammupandu_57
writerConfig.connectOptions.connectTimeout = 2000
writerConfig.connectOptions.useAffectedRows = true
writerConfig.connectOptions.cachePreparedStatements = true
writerConfig.poolOptions.maxSize = 3
writerConfig.poolOptions.maxWaitQueueSize = 2000
writerConfig.retryCount = 3
