readerConfig.connectOptions.host = "localhost"
readerConfig.connectOptions.port = 3306
readerConfig.connectOptions.database = "experiment"
readerConfig.connectOptions.user = ${MYSQL_USER}
readerConfig.connectOptions.password = ${MYSQL_PASSWORD}
readerConfig.connectOptions.connectTimeout = 2000
readerConfig.connectOptions.useAffectedRows = true
readerConfig.connectOptions.cachePreparedStatements = true
readerConfig.poolOptions.maxSize = 5
readerConfig.poolOptions.maxWaitQueueSize = 2000
readerConfig.retryCount = 3

writerConfig.connectOptions.host = "localhost"
writerConfig.connectOptions.port = 3306
writerConfig.connectOptions.database = "experiment"
writerConfig.connectOptions.user = ${MYSQL_USER}
writerConfig.connectOptions.password = ${MYSQL_PASSWORD}
writerConfig.connectOptions.connectTimeout = 2000
writerConfig.connectOptions.useAffectedRows = true
writerConfig.connectOptions.cachePreparedStatements = true
writerConfig.poolOptions.maxSize = 3
writerConfig.poolOptions.maxWaitQueueSize = 2000
writerConfig.retryCount = 3
