readerConfig.connectOptions.host = ${mysql.host}
readerConfig.connectOptions.port = ${mysql.port}
readerConfig.connectOptions.database = ${mysql.database}
readerConfig.connectOptions.user = ${mysql.user}
readerConfig.connectOptions.password = ${mysql.password}

writerConfig.connectOptions.host = ${mysql.host}
writerConfig.connectOptions.port = ${mysql.port}
writerConfig.connectOptions.database = ${mysql.database}
writerConfig.connectOptions.user = ${mysql.user}
writerConfig.connectOptions.password = ${mysql.password}
