host="localhost"
host=${?AEROSPIKE_HOST}
port=3030
maxRetries=3
maxConnsPerNode=700
eventLoopSize=16
maxCommandsInProcess=40
maxCommandsInQueue=100
connectRetryIntervalMS=5000

namespace="experiment"
namespace=${?NAMESPACE}
userAllocationsSet="allocation"
variantCountSet="variantCount"
reallocationLogSet="reallocationLog"
reallocationLogBin="logs"
userLockSet="userLock"
variantCountBin="count"
userAllocationLockBin="locked"
allocationMapBin="allocationMap"