host="testlab-aerospike"${TEAM_SUFFIX}"."${PRIVATE_HOSTED_ZONE}
port=3000
maxRetries=3
maxConnsPerNode=700
eventLoopSize=16
maxCommandsInProcess=40
maxCommandsInQueue=100
connectRetryIntervalMS=5000
namespace="your-namespace"