host="localhost"
host=${?AEROSPIKE_HOST}
port=3000
maxRetries=3
maxConnsPerNode=700
eventLoopSize=16
maxCommandsInProcess=40
maxCommandsInQueue=100
connectRetryIntervalMS=5000

namespace="experiment"
namespace=${?NAMESPACE}
userAssignmentsSet="userAssignment"
variantCountSet="variantCount"
userLockSet="userLock"
countBin="count"
lockBin="locked"
assignmentMapBin="assignmentMaps"
