cohortsConfig.serviceURL="flockr-users:8080"
cohortsConfig.serviceURL=${?COHORTS_URL}
cohortsConfig.apiEndPoint="/flockr/users/get-cohorts"
cohortsConfig.apiEndPoint=${?GET_COHORT_API}
cohortsConfig.apiTimeoutMS=10

projectKey="47f96fce-e1f1-4a32-9f53-6502b122ff75"
projectKey=${?PROJECT_KEY}
