cohortsConfig.serviceURL="localhost:8081"
cohortsConfig.serviceURL=${?COHORTS_URL}
cohortsConfig.apiEndPoint="/v1/cohorts/realtime"
cohortsConfig.apiEndPoint=${?GET_COHORT_API}
cohortsConfig.apiTimeoutMS=500

projectKey="47f96fce-e1f1-4a32-9f53-6502b122ff75"
projectKey=${?PROJECT_KEY}
