bootstrapServer="testlab-kafka"${TEAM_SUFFIX}"."${PRIVATE_HOSTED_ZONE}":9092"
keySerializerClass="org.apache.kafka.common.serialization.StringSerializer"
valueSerializerClass="org.apache.kafka.common.serialization.StringSerializer"
acks="1"
topic="your-topic"
